### ISSUE TITLE
插件界面显示以及插件文档引用

### ISSUE THREAD

**Issue by HopeLHP** [zuoez02/siyuan-plugin-excalidraw#1]
1、新建Excalidraw后Excalidraw界面只占编辑器界面的一半不到？
<img width="1213" alt="image" src="https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/70339118/bfc298c1-17dc-405a-8cf9-c593ab49ea27">
2、另外，插件生成Excalidraw是不能被文档搜索、引用或嵌入吗？

**Comment by zuoez02** [comment]
1. 问题已修复与0.1.4，等集市更新吧
2. 搜索目前没有API可以介入，引用和嵌入正在开发中，也需要思源API配合。

**Comment by HopeLHP** [comment]
好的，感谢插件
