### ISSUE TITLE
在2.9.5版本中无法使用

### ISSUE THREAD

**Issue by Joker-lkc** [zuoez02/siyuan-plugin-excalidraw#13]
在2.9.5版本中无法使用

**Comment by zuoez02** [comment]
能看一下控制台是否有错误吗？我这本地无法复现

**Comment by Joker-lkc** [comment]
![image](https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/56438623/4f9fbebe-079e-43d2-8d24-8e5d971a52b7)
![image](https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/56438623/006f33dd-d5be-45f8-9f01-e2b75716bf2e)
没有看到明显的报错，主要没有使用的位置。

**Comment by zuoez02** [comment]
不是这个。在其他地方找到了问题，已经提交了v0.3.2修复这个问题。

**Comment by zuoez02** [comment]
资源变成外网加载导致的错误。

**Comment by Joker-lkc** [comment]
好的，辛苦，大概什么时候可以更新呢

**Comment by zuoez02** [comment]
已经提交了，等一个小时左右，思源也需要重启一下才能获取到更新。这个频率是由思源本身决定的，而不是插件。
