### ISSUE TITLE
安装Excalidraw插件后，没找到相关打开入口

### ISSUE THREAD

**Issue by jokizhu** [zuoez02/siyuan-plugin-excalidraw#14]
软件版本：2.9.6，按照提供使用方法“在 Excalidraw Dock 右上角点击“+”创建 Excalidraw 画板后，点击即可使用。”，但安装后，没找到打开该软件入口地方，可能是什么原因？（补充：安装其它插件，在软件右上角“插件”内可以看到，但这个Excalidraw没看到）
![image](https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/128120301/17660deb-304d-40e8-b8f7-45f2a41c32ce)
![image](https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/128120301/d8c3241a-cb03-4b87-a49c-a158969d041b)

**Comment by Coande** [comment]
遇到同样的问题，怎么 close 了呢

**Comment by Coande** [comment]
> > 遇到同样的问题，怎么 close 了呢
> 
> @Coande 重启一下思源，左下角dock找到excalidraw的dock

感谢，原来在左下角
