### ISSUE TITLE
增加 支持中文手写效果的draw？

### ISSUE THREAD

**Issue by Geo123abc** [zuoez02/siyuan-plugin-excalidraw#17]
考虑兼容或者再做一个支持中文手写效果的draw吗？

在少数派看到的  [大厂程序员都在用什么工具绘图？Handraw: 支持中文手写效果的 Excalidraw - 少数派](  https://sspai.com/post/80459  )    

Excalidraw 是一个非常强大的手绘效果的白板工具，一经推出，就非常火爆、广受欢迎。但是作为中文用户，在使用中却没有中文手绘效果，这是接受不了的。另外，只有单画布能力也大大限制了我们日常的使用效率。

因此，作者基于开源 Excalidraw 进行了能力增强，并推出了免费线上服务[Handraw | 中文友好的手写效果白板工具](  https://handraw.top/  )     和开源项目 [korbinzhao/excalidraw-cn: Excalidraw-CN 是支持中文手写和多画布的 Excalidraw 白板工具。Excalidraw-CN is a whiteboard supporting Chinese hand draw font and multi-canvas based on Excalidraw.](  https://github.com/korbinzhao/excalidraw-cn  )    （欢迎 star）。欢迎大家免费使用。

**Comment by zuoez02** [comment]
中文手写效果，说的就是文字字体支持中文字体，插件已经支持了，第四个字体就是。

**Comment by Geo123abc** [comment]
> 中文手写效果，说的就是文字字体支持中文字体，插件已经支持了，第四个字体就是。

OKKKK，我去试试，谢谢
