### ISSUE TITLE
文件保存

### ISSUE THREAD

**Issue by mzcxiaohuanxiong** [zuoez02/siyuan-plugin-excalidraw#2]
请问一下，创建的文件保存在本地哪个文件。好像也不支持思源的同步？

**Comment by zuoez02** [comment]
保存在工作空间/data/storage/petals/siyuan-plugin-excalidraw/下，支持同步

**Comment by mzcxiaohuanxiong** [comment]
很棒，谢谢大佬。要是支持思源的链接和引用就更完善了。就是思源白板的平替。已star，希望能继续开发，也可以付费。嘿嘿




小孟
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zuoez02/siyuan-plugin-excalidraw"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月9日(星期五) 上午9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zuoez02/siyuan-plugin-excalidraw] 文件保存 (Issue #2)





 
保存在工作空间/data/storage/petals/siyuan-plugin-excalidraw/下，支持同步
