### ISSUE TITLE
安装后不显示 dock，重启了也不行

### ISSUE THREAD

**Issue by itachaaa** [zuoez02/siyuan-plugin-excalidraw#20]
![image](https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/31896600/174d2489-2486-4c1f-bf54-a65c2772de51)

当前版本 v2.10.0

**Comment by zuoez02** [comment]
左下角找找

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: licheng ***@***.***>
发送时间: Sunday, August 20, 2023 3:39:32 PM
收件人: zuoez02/siyuan-plugin-excalidraw ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zuoez02/siyuan-plugin-excalidraw] 安装后不显示 dock，重启了也不行 (Issue #20)


[image]<https://user-images.githubusercontent.com/31896600/261838588-174d2489-2486-4c1f-bf54-a65c2772de51.png>

当前版本 v2.10.0

―
