### ISSUE TITLE
无法显示

### ISSUE THREAD

**Issue by LakeHP** [zuoez02/siyuan-plugin-excalidraw#3]
![image](https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/136073046/103e4f8b-0d09-45a4-9459-e6a29a332a6c)

安卓端开伺服，电脑端浏览器访问会出现无法打开的情况

**Comment by zuoez02** [comment]
伺服目前无法支持

**Comment by zuoez02** [comment]
更新到0.2.8，已经可以网络伺服使用了
