### ISSUE TITLE
文件创建优化

### ISSUE THREAD

**Issue by bgppseries** [zuoez02/siyuan-plugin-excalidraw#5]
很棒的插件，一直想试验画布了，就是创建文件的时候，输入文件名之后不能用回车保存，还得用鼠标点，不知道这个能否优化
![image](https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/77733052/34737540-97e5-43d7-b145-4b796bfe902e)
还有我想问下这个支持数位板吗

**Comment by zuoez02** [comment]
1. 可以优化
2. 我没有数位板设备可供测试，不过excalidraw是支持触屏的，并且支持压感，理论上应该可以？

**Comment by pisceswb** [comment]
支持数位板，有压感，但笔比较粗，需要缩放画布后，才能正常写字

**Comment by zuoez02** [comment]
粗细问题关联到 https://github.com/zuoez02/siyuan-plugin-excalidraw/issues/4
