### ISSUE TITLE
超链接问题

### ISSUE THREAD

**Issue by Achuan-2** [zuoez02/siyuan-plugin-excalidraw#6]
![image](https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/60436214/75e6adcb-0a8f-4196-8e23-53e4375fd22c)
右上角的超链接无法打开，实际为about
![image](https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/60436214/bf67c9b7-3d2a-45c0-8bdb-6e9186b29661)

**Comment by zuoez02** [comment]
感谢回复，v0.2.1已修复这个问题，请等待新版本升级包。
