### ISSUE TITLE
麻烦大神抽空向D大提一下引用和嵌入的API需求，辛苦！

### ISSUE THREAD

**Issue by ippreacher** [zuoez02/siyuan-plugin-excalidraw#7]
![_20230615113525](https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/53852556/53f2a351-4473-4c22-ba36-c84f90fc8980)
![_20230615113536](https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/53852556/ef340eea-3971-4bc8-a297-d15cc212bbfa)

**Comment by zuoez02** [comment]
提了，https://github.com/siyuan-note/siyuan/issues/8544

**Comment by ippreacher** [comment]
辛苦了，感谢！
