### ISSUE TITLE
重命名功能

### ISSUE THREAD

**Issue by frostime** [zuoez02/siyuan-plugin-excalidraw#8]
今天突然想要重命名一个已经创建的 draw发现没有提供功能。结果我打开源码看，renameDraw 是实现了的。
![image](https://github.com/zuoez02/siyuan-plugin-excalidraw/assets/27268127/e622eb49-af2f-4d79-b6a9-b19792617851)

z是不是忘了把这个 renameDraw 挂载到dom事件上去了。

**Comment by zuoez02** [comment]
嗯，写了一半
